# Generated by Django 3.2.9 on 2021-12-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_limit', models.IntegerField()),
                ('lower_limit', models.IntegerField()),
                ('doc', models.FileField(default='', upload_to='')),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
