# Generated by Django 4.0.6 on 2022-07-17 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='doc',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
