# Generated by Django 4.0.1 on 2022-01-26 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('doc', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('email', models.EmailField(default=None, max_length=254)),
                ('dummy', models.TextField()),
            ],
        ),
    ]
